export { default as AdminLayout } from './AdminLayout'
export { default as Dashboard } from './Dashboard'
export { default as ManageFlight } from './ManageFlight'
// export { default as ManageAirport } from './ManageAirport'
export { default as ManageUser } from './ManageUser'
// export { default as FlightDetail } from './FlightDetail'
export { default as CreateFlight } from './CreateFlight'
export { default as ManageBooking } from './ManageBooking'
export { default as ManageInvoice } from './ManageInvoice'
export { default as Test } from './Test'