const actionTypes = {
    LOGIN: 'LOGIN',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT: 'LOGOUT',

    GET_FLIGHTS: 'GET_FLIGHTS',

    UPDATE_DATA: 'UPDATE_DATA',

    RESET_DATAUPDATE: 'RESET_DATAUPDATE',

    SEARCH_FLIGHTS: 'SEARCH_FLIGHTS',

    GET_AIRPORTS: 'GET_AIRPORTS',

    GET_AIRLINES: 'GET_AIRLINES',

    //USER
    GET_CURRENT: 'GET_CURRENT',
    GET_USERS: 'GET_USERS',


}

export default actionTypes